---
site_name: Poietic Generator Documentation
site_url: 'https://poietic-generator.github.io/poietic-generator-documentation/'
site_author: 'Glenn Y. Rolland', 'Olivier Auber'

repo_name: 'Source'
repo_url: 'https://github.com/poietic-generator/poietic-generator-documentation'

theme:
  name: 'material'
  logo: images/logo.png
  language: en
  palette:
    - scheme: default
      primary: teal
      accent: black
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight

extra:
  search:
    language: 'fr, en'

markdown_extensions:
  - footnotes
  - admonition
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - search
  - include-markdown
  - awesome-pages
  - glightbox

extra_css:
  - css/extra.css

extra_javascript:
  - js/extra.js

nav:
  - Home: index.md
  # Ajoutez ici la structure de votre documentation

# author:
#   github: 'glenux'
#   twitter: 'glenux'

# Extensions
markdown_extensions:
  - footnotes
  - admonition
  - toc:
      permalink: '#'
  - codehilite:
      guess_lang: false

  # pip install mdx_truly_sane_lists
  - mdx_truly_sane_lists

  # pip install pymdown-extensions
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
      #
  # pip install pymdown-extensions
  - pymdownx.superfences:

plugins:
  - include-markdown
  - awesome-pages
  - glightbox

extra:
  search:
    language: 'fr, en'

# run the following line to update toc
# pipenv run ./script/update-toc
